app = "todo-haiku"
primary_region = "ord" # Chicago - change this to whatever region you prefer
kill_signal = "SIGTERM"

[env]
  PHX_HOST = "todo-haiku.fly.dev"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 500

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[mounts]
  source = "todo_haiku_data"
  destination = "/data" 